language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

install:
    - composer install --prefer-source

before_script:
    - composer self-update

script:
    - bin/phpunit -c phpunit.xml.dist